### ISSUE TITLE
유스케이스 결합 분리

### ISSUE THREAD

**Issue by shinsunyoung** [Coveong/reading-books-for-programmers#10]
# 📖 Reference

16장 독립성 160쪽

유스케이스는 시스템을 분할하는 매우 자연스러운 방법이다.

유스케이스는 시스템의 수평적인 계층을 가로지르도록 자른, 수직으로 좁다란 조각이기도 하다. 각 유스케이스는 UI의 일부, 애플리케이션 특화 업무 규칙의 일부, 애플리케이션 독립적 업무 규칙의 일부, 그리고 데이터베이스 기능의 일부를 사용한다. 따라서 우리는 시스템을 수평적 계층으로 분할하면서 동시에 해당 계층을 가로지르는 얇은 수직적인 유스케이스로 시스템을 분할할 수 있다.

#  ❔ Question

이 부분의 내용이 이해가 안가는데 혹시 이해 가신분 ... 설명 부탁드림니다 ... 😭

**Comment by wisemuji** [comment]
저는 클린 아키텍처 책을 읽기 전에 유스케이스 강의를 들었어서 이 부분이 이해가 잘 갔어요! 유스케이스에 대해서 기본적인 개념을 이해한 후에 다시 읽어보시면 훨씬 도움이 될거에요.

이 글을 추천드려요.
https://alphahackerhan.tistory.com/28

다 읽으신 후에 다음 그림으로 정리해보세요! @shinsunyoung 
![image](https://user-images.githubusercontent.com/32327475/120997634-56df7500-c7c2-11eb-9531-38ba5e392670.png)

**Comment by shinsunyoung** [comment]
숙제인가요 ... ?? 알겠읍니다 ...

**Comment by HongEunbeen** [comment]
오,, 지금 20장 업무규칙 읽으면서 보고 있는데 글이 굉장히 도움이 되네요,,
