### ISSUE TITLE
객체지향의 핵심은 클래스가 객체가 위치한다

### ISSUE THREAD

**Issue by shinsunyoung** [Coveong/reading-books-for-programmers#3]
# 📖 Reference

1장 38쪽

객체지향의 중심에는 클래스가 아니라 객체가 위치하며, 중요한 것은 클래스들의 정적인 관계가 아니라 주고받는 객체들의 동적인 관계다.

#  ❔ Question

클래스를 중점으로 생각하는 것과 객체를 중점으로 생각하는것이 뭐가 다른건가요?? 클래스가 아닌 객체를 중심으로 생각하라는게 이해가 잘 안가용 ㅍ... 😨

**Comment by HongEunbeen** [comment]
- 코드를 담는 클래스의 관점 → 메시지를 주고받는 객체의 관점 사고의 중심 전환

- 어떤 클래스가 필요한가 x → 어떤 객체들이 어떤 메시지를 주고받으며 협력할 것인가
- **클래스는 객체들의 협력 관계를 코드로 옮기는 도구에 불가**

책에서는 클래스는  콜라, 사람, 점원 이런식으로 사물을 코드에 담는다는 뜻을 사용하는것 같고 객체는 콜라를 주문하는 사람, 콜라 주문을 받는 점원, 사람이 마시는 콜라 이런식으로 객체들 간의 메시지를 생각할 수 있는 것 같습니다!!

**Comment by shinsunyoung** [comment]
오 ~~~~~~ 비유가 너무 적절해서 이해가 쏙쏙됐네용 감사합니다 😆
