### ISSUE TITLE
protected 변수를 피해야 하는 이유

### ISSUE THREAD

**Issue by HongEunbeen** [Coveong/reading-books-for-programmers#4]
# 📖 Reference

5장 101쪽 수직 거리 부분

서로 밀접한 개념은 세로로 가까이 둬야 한다. 물론 두 개념이 서로 다른 파일에 속한다면 규칙이 통하지 않는다. 하지만 타당한 근거가 없다면 서로 밀접한 개념은 한 파일에 속해야 마땅하다. 이게 바로 protected 변수를 피해야 하는 이유 중 하나다.

#  ❔ Question

protected 변수 - 동일 패키지내의 클래스 또는 해당 클래스를 상속받은 외부 패키지의 클래스에서 접근이 가능하다.
라는 개념으로 알고 있는데 protected 변수를 피해야 하는 이유를 모르겠습니다,,! 상속과 관련된 문제인가요?

**Comment by shinsunyoung** [comment]
상속과 관련된 문제라고 볼 수 있을 것 같아요! `protected`로 접근지정을 하는 이유가 하위 클래스에서 접근이 가능하게 하려고 하는건데, 밀접한 개념을 한 파일에 넣지 않고 **상속을 이용해 파일을 분리한 후 `protected`를 사용하는 것은 결국 밀접한 개념을 다른 파일로 분리**시키는 것과 다름없기 때문에 파일의 코드 수를 줄여줄 뿐, 좋지 않은 설계라고 보기 때문이 아닐까요??
