### ISSUE TITLE
밥 아저씨의 형식 규칙 예제 코드의 의문점 질문!

### ISSUE THREAD

**Issue by HongEunbeen** [Coveong/reading-books-for-programmers#5]
# 📖 Reference

5장 114페이지 밥 아저씨의 형식 규칙 부분 (목록 5-6 예제 코드)

```java
public int getMedianLineWidth() {
	Integer[] sortedWidths = getSortedWidths();
	int cumulativeLineCount = 0;
	for (int width : sortedWidths) {
		cumulativeLineCount += lineCountForWidth(width);
		if (cumulativeLineCount > lineCount)
			return width;			
	}
	throws new Error("Cannot get here");
}

private int lineCountForWidth(int width) {
	return lineWidthHistogram.getLinesforWidth(width).size();
}

private Integer[] getSortedWidths() {
	Set<Integer> widths = lineWidthHistogram.getWidths();
	Integer[] sortedWidths = (widths.toArray(new Integer[0]));
	Arrays.sort(sortedWidths);
	return sortedWidths;
}
```

#  ❔ Question

예제 코드의 마지막 부분인데 **종속 관계의 함수는 수직적으로 가까이 존재**한다는 개념에 따라 `getMedianLineWidth()` 함수에서 `getSortedWidths()` 함수를 먼저 호출하게 되니 후에 호출되는 `lineCountForWidth(int width)`의 함수가 더 아래에 작성되어야 맞는거 같은데 더 밑에 작성되어 질문합니다!!
 혹시 이 부분이 저차원함수와 세부 내역으로 분류되어 **저차원함수와 세부내역은 가장 마지막에 존재한다는 개념**에 따라 `getMedianLineWidth()` 가 더 밑 부분에 작성된건가요?

**Comment by shinsunyoung** [comment]
이 부분은 저도 `getSortedWidths()`가 위로 올라와야 하는 것 같은데 잘 모르겠네요 ... 월요일에 읽어보고 다시 코멘트 달아보도록 하겠습니당 ㅎㅎㅎ
