### ISSUE TITLE
(질문 아님)(참고글) 컴파일 시점 의존성과 런타임 시점 의존성

### ISSUE THREAD

**Issue by wisemuji** [Coveong/reading-books-for-programmers#6]
# 📖 Reference

2장 57쪽

> 클래스 사이의 의존성과 객체 사이의 의존성은 다를 수 있다.
클래스 사이의 의존성과 객체 사이의 의존성이 다를수록 코드를 이해하기 어려워지고 디버깅하기 어려워진다.
반면에 코드는 더 유연해지고 확장 가능성이 높아진다. -> 설계가 트레이드오프의 산물

#  ❕ 참고글

혹시 코틀린 공부하시는 분 중에 2장에서 설명하는 컴파일 시점 의존성과 런타임 시점 의존성에 대해 더 자세히 알고 싶으신 분들은 
https://proandroiddev.com/kotlin-lambda-vs-method-reference-fdbd175f6845 이 글 읽어보시면 좋을 것 같아요!

Kotlin lambda와 method reference의 차이에 대해 설명하고 있는데 꼭 책에서 설명하고 있는 예시 외에도 컴파일 시점 의존성과 런타임 시점 의존성이 생길 수 있다는 점을 공유드리고 싶었어요.

한글로 정리한 번역본입니다:
https://www.notion.so/Kotlin-lambda-method-reference-068c05c3fba04814b5f75d47a3611e9c

**Comment by shinsunyoung** [comment]
👍👍👍

**Comment by shinsunyoung** [comment]
람다와 메서드 참조 방식을 비교한 글을 읽다보니 소개 시켜드리고 싶은 글(?)이 있어 코멘트를 작성합니다! ([이펙티브 자바43. 람다보다는 메서드 참조를 사용하라](https://github.com/Meet-Coder-Study/book-effective-java/blob/main/7%EC%9E%A5/43_%EB%9E%8C%EB%8B%A4%EB%B3%B4%EB%8B%A4%EB%8A%94_%EB%A9%94%EC%84%9C%EB%93%9C_%EC%B0%B8%EC%A1%B0%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%ED%99%A9%EC%A4%80%ED%98%B8.md)) 의존성과는 관계가 없지만 가볍게 읽기 좋으니 시간 있으실 때 읽어보시면 좋을 것 같아요ㅎㅎ 😆😆 람다와 메서드 참조로 생성한 인스턴스의 생성시점이 다른건 처음 알았네요!  

+ 제가 링크한 글에 첨언을 하자면 람다보다 메서드 참조를 선호 하는 또 다른 이유로는 람다보다 메서드 참조가 TDA(Tell Dont Ask)를 만족하기도 해서 인 것 같아요!
