### ISSUE TITLE
DTO는 '객체'일까요 '값'일까요?

### ISSUE THREAD

**Issue by shinsunyoung** [Coveong/reading-books-for-programmers#7]
# 📖 Reference

객체지향의 사실과 오해 2장 57쪽
> 객체란 인간의 인지 능력을 이용해 식별 가능한 경계를 가진 모든 사물을 의미한다. 객체가 식별 가능하다는 것은 객체를 서로 구별할 수 있는 특정한 프로퍼티가 객체 안에 존재한다는 것을 의미한다. 모든 객체가 식별자를 가진다는 것은 반대로 객체가 아닌 단순한 값은 식별자를 가지지 않는다는 것을 의미한다.
...
값과 객체의 가장 큰 차이점은 값은 식별자를 가지지 않지만 객체는 식별자를 가진다는 점이다.

> 값(value)은 변하지 않는 양을 모델링한다. 흔히 값의 상태는 변하지 않기 때문에 불변 상태를 가진다고 말한다.

#  ❔ Question

DTO는 가변 상태이며, getter/setter를 제외한 로직을 포함할 수 없다고 알고 있습니다.
또한, DTO는 객체 자체의 고유한 특성을 가지고 있기 때문에(DTO dto1(1) ≠ DTO dto2(1)) 식별 가능한 경계를 가지고 있다고 생각됩니다.

DTO의 특징만 봤을 때 DTO는 책에서 서술하는 '객체'에 속하는 것 같은데, getter/setter만 가질 수 있다는 특징을 생각하면 객체의 자율성이 없고 자기 자신을 책임지지 못하기 때문에 '값'에 속하는 것도 같네요 😭

DTO는 객체지향의 사실과 오해에서 서술하는 '객체'에 속하는 것일까요, '값'에 속하는 것일까요?  아니면 책에서 소개하지 않는 다른 범주가 있는 것일까요?
hoxy ... 답을 아시는 분이 있으면 코멘트를 남겨주시면 감사하겠습니다. 🙇‍♀️🙇‍♀️

**Comment by wisemuji** [comment]
DTO는 객체라고 생각합니다!

DTO에 비즈니스 로직이 들어가면 안되는건 맞지만 비즈니스 로직 외에 간단한 타입 변환(FLOAT을 DOUBLE로 변환하는 등) 작업이나 nullable을 not nullable하게 변환하는 작업 등은 가능하다고 생각해요. 그리고 그 역할을 할 수 있다는 것은 객체 자신이 그의 자율성을 갖고 책임진다는 의미와 다를바없다고 봅니다.

무엇보다도 본문에 첨부해주신 것처럼 객체지향의 사실과 오해 책에서는 객체와 값의 가장 큰 차이가 식별자의 유무라고 말하고 있는데 프로퍼티를 갖는 DTO가 값으로 취급된다면 이 특징을 위반하게 되는 것 같습니다. 

아무 함수도 없고 프로퍼티와 getter/setter만 존재하는 일반 클래스도 객체로 취급하는 것처럼 DTO도 동일한 맥락이라고 생각해요!

+) DTO가 가변 상태라고 하셨는데 개인적으로 DTO의 값은 가변성을 제한하고 불변하게 다뤄야 한다고 생다해용!

**Comment by shinsunyoung** [comment]
답변 감사합니다!
그렇다면 DTO의 식별자는 hashCode가 되는걸까요? 책에서 객체라고 말했던 엔티티같은 경우에는 뚜렷한 식별자(id)가 있는데, 그에 비해 DTO는 식별자라고 할만한게 hashCode밖에 없는 것 같아서욥!

그리고 이것도 제 의견이긴 한데 저는 만약 DTO를 '객체'로 바라보게 된다면 불변이 아니라 가변으로 다뤄야한다고 생각해요! 객체가 가질 수 있는 특징 중에 변경 가능한 상태가 있는데 DTO를 불변으로 다루게 되면 객체로 볼 수 없다고 생각하기 때문임니다 ... !! (혹시나 다른 이유가 있으면 알려주세용!!)

**Comment by wisemuji** [comment]
> 그렇다면 DTO의 식별자는 hashCode가 되는걸까요? 책에서 객체라고 말했던 엔티티같은 경우에는 뚜렷한 식별자(id)가 있는데, 그에 비해 DTO는 식별자라고 할만한게 hashCode밖에 없는 것 같아서욥!

hashCode의 경우 설계 레벨이 아닌 코드 구현 레벨에서 고민해야 하는게 아닐까용? DTO의 식별자를 꼭 hashcode로 정의할 수는 없을 것 같아요! 식별자가 무엇이 될지는 저도 잘 모르겠네요 🤔 

> 그리고 이것도 제 의견이긴 한데 저는 만약 DTO를 '객체'로 바라보게 된다면 불변이 아니라 가변으로 다뤄야한다고 생각해요! 객체가 가질 수 있는 특징 중에 변경 가능한 상태가 있는데 DTO를 불변으로 다루게 되면 객체로 볼 수 없다고 생각하기 때문임니다 ... !! (혹시나 다른 이유가 있으면 알려주세용!!)

가변성 제한에 대해서는 이팩티브 자바/코틀린에서 설명하고 있습니다! https://aroundck.tistory.com/596 이 글을 참고해보시면 좋을 것 같아요. 그리고 '객체가 가질 수 있는 특징 중에 변경 가능한 상태'가 있다고 하셨는데 레퍼런스나 책 페이지를 첨부해주실 수 있을까요?

+) 또 '객체를 도와주는 단순 클래스'가 DTO의 정의라면 그것 역시 하나의 책임으로 생각할 수 있을 것 같아요. DTO 객체의 책임 -> 값을 운반하는 것이라고 보면 어떨까요?

**Comment by shinsunyoung** [comment]
> 그리고 '객체가 가질 수 있는 특징 중에 변경 가능한 상태'가 있다고 하셨는데 레퍼런스나 책 페이지를 첨부해주실 수 있을까요?
객체지향의 사실과 오해 59p에 있습니다!
- 객체는 상태를 가지며 상태는 변경 가능하다

좋은 의견 주셔서 감사합미다 ... 🤓

**Comment by shinsunyoung** [comment]
https://jojoldu.tistory.com/407
> 같이 일을 하다보면 누군가가 생성자를 수정할일이 생기는데,
사용하는곳을 확인해보면 테스트 코드에서만 사용하는줄 알고 수정했다가
배포하고 문제가 발견할때가 있어서요.
사용하는 곳이 여러개인데, 그중 한군데는 코드상에서 확인이 어렵다면
저는 실수할 여지가 많다고 봐요.
그래서 사용하는 곳이 명시적으로 있는게 좋다고 봅니다.

DTO 불변에 대한 이야기입니다!
저는 개인적으로 위 의견에 동의하고, 링크를 걸어주신 불변 객체에 대한 이야기에도 동의합니다.  지금 제 생각으로는 Controller Layer - Business Layer에 사용하는 DTO에 불변을 보장할 필요는 없지만, Business Layer - Persistance Layer에 사용하는 DTO에 불변성을 보장하는 것도 좋은 것 같네요 :) (개인적인 의견입니당!)
