### ISSUE TITLE
값을 포장하는 클래스에 대한 의문

### ISSUE THREAD

**Issue by wisemuji** [Coveong/reading-books-for-programmers#8]
# 📖 Reference

책과 직접적인 연관이 있지 않아 페이지 첨부를 생략합니다.

#  ❔ Question

값을 포장하는 클래스에 대해 의문이 생겨서 질문을 남깁니다. 

```java
class Position {
   private int position;
}
```

다음과 같이 클래스 내에 다른 책임이나 역할이 없고 오직 값에 대한 프로퍼티 하나만 존재하는 클래스를 종종 사용하는데요, 이게 과연 어떤 의미가 있을까요? 명시적인 의미를 부여한다고 생각할 수 있지만 변수명으로 대체하더라도 충분히 의미를 제공할 수 있다고 생각합니다. 혹시 다른 분들은 어떻게 생각하시나요?

**Comment by shinsunyoung** [comment]
`객체지향의 사실과 오해`에 내용이 있는줄 알았는데 `DDD Start!`에 있네요

> 밸류 타입이 꼭 두 개 이상의 데이터를 가져야하는 것은 아니다. 의미를 명확하게 표현하기 위해 밸류 타입을 사용하는 경우도 있다.

```
// 여기서 뭐가 '돈'을 의미하는지 알기 어려움
public class OrderLine {
    private Product product;
    private int price;
    private int quantity;
    private int amounts;
}

// price, amounts가 '돈'을 의미하는 것을 알 수 있음
public class OrderLine {
    private Product product;
    private Money price;
    private int quantity;
    private Money amounts;
}
```
물론 변수명으로 대체할 수 있겠지만, 저는 일반 데이터 타입 + 변수명만으로는 의미 제공에 한계가 있을 수 있다고 생각합니다. 위 예시 같은 경우에도 당연히  `quantity`는 개수의 의미를 가지고 있으니 `price`, `amounts`가 돈이라는 의미를 가지고 있을 수 있다고 생각할 수 있지만, 저는 이런 경우가 생길 수도 있다고 생각합니다. (만약 다르게 생각한다면 코멘트 부탁드려요!)
1. 유지보수 하는 사람이 `quantity`의 뜻을 모른다면?
2. `amounts`의 의미를 '총액'의 의미가 아닌, '양'의 의미로 착각한다면?


> 또 다른 장점은 밸류 타입을 위한 기능을 추가할 수 있다. (Money라면, 돈 계산을 위한 기능을 추가할 수 있다.)
이건 이견이 없을 것 같아 따로 추가 설명을 붙이지 않겠습니당
---

[객체지향 생활 체조 규칙 3번](https://developerfarm.wordpress.com/2012/01/27/object_calisthenics_4/)에도 이에 대한 내용이 명시되어있네요! 참고해보면 좋을 것 같습니당

**Comment by wisemuji** [comment]
우왕! 자세한 레퍼런스와 코드를 첨부해주셔서 이해가 아주 잘 되었습니다 😊 

더 이견은 없습니다! 일반 데이터 타입 + 변수명만으로는 의미 제공에 한계가 있을 때 해당 방법을 사용해야겠네요. 이참에 객체지향 생활 체조 규칙을 다시 한 번 환기해야겠어요! 감사합니다 🙇 🙇 🙇

**Comment by wisemuji** [comment]
이 이슈는 닫겠습니다.
