### ISSUE TITLE
객체는 실세계에 존재한다 vs 객체지향은 현실 세계에 대한 은유다

### ISSUE THREAD

**Issue by shinsunyoung** [Coveong/reading-books-for-programmers#9]
# 📖 Reference

2장 67쪽

이것은 소프트웨어 상품이 실제 세계의 상품을 단순화하거나 추상화한 것이 아니라 특성이 전혀 다른 어떤 것임을 의미한다. (은유)
객체가 현실 세계에 존재한다. 

---

[좋은 객체의 7가지 덕목](https://codingnuri.com/seven-virtues-of-good-object)

먼저, 객체는 생명체다. 게다가 객체는 의인화, 즉 인간처럼 취급해야 한다(또는 애완동물을 선호한다면 애완동물처럼)

#  ❔ Question
둘의 의견이 상반되는 내용인 것 같은데, 현실 세계와 객체 사이의 연관관계에 대한 여러분의 생각이 궁금합니다! 👀

**Comment by wisemuji** [comment]
@shinsunyoung 혹시 어떤 책인가용? 라벨 달아주실 수 있을까여?

**Comment by shinsunyoung** [comment]
객체지향의 사실과 오해입니당! 오브젝트는 관련된 책이어서 추가했어요

**Comment by wisemuji** [comment]
@shinsunyoung 
> 둘의 의견이 상반되는 내용인 것 같은데, 현실 세계와 객체 사이의 연관관계에 대한 여러분의 생각이 궁금합니다! 👀

저는 둘의 의견이 상반된다고 생각하지 않습니다!

오브젝트 1장 33쪽에 보면 다음과 같이 설명하고 있습니다.
> 비록 현실에서는 수동적인 존재라고 하더라도 일단 객체지향의 세계에 들어오면 모든 것이 능동적이고 자율적인 존재로 바뀐다. 레베카 워프스브록은 이처럼 능동적이고 자율적인 존재로 소프트웨어 객체를 설계하는 원칙을 가리켜 **의인화**라고 한다.

첨부해주신 [좋은 객체의 7가지 덕목](https://codingnuri.com/seven-virtues-of-good-object)에서도 다음과 같이 설명하고 있습니다.
> 먼저, 객체는 생명체다. 게다가 객체는 의인화, 즉 인간처럼 취급해야 한다(또는 애완동물을 선호한다면 애완동물처럼). 이것은 기본적으로 객체가 자료구조나 함수의 집합이 아니라는 것을 의미한다. 그 대신 객체는 자신만의 생명주기, 행위, 습관을 지닌 독립적인 개체다.

두 의견을 종합해봤을 때 객체는 현실 세계에서 수동적인 개념이라도 '능동적으로 책임을 갖고 행동하는 독립적인 존재로 인식'하면 된다는 것으로 보면 될 것 같아요. 따라서 현실 세계에서 개념을 가져오더라도 현실세계 그대로 이해하지 않고 '능동적으로 책임을 갖고 행동하는 독립적인 존재로 인식'하자는게 결론인 것 같습니다!

**Comment by shinsunyoung** [comment]
의견 감사합니다! [좋은 객체의 7가지 덕목](https://codingnuri.com/seven-virtues-of-good-object/)에는 이런 이야기도 있는데,
> 컨트롤러, 파서, 필터, 검증기, 서비스 로케이터, 싱글턴, 팩터리는 좋은 객체가 아니다. 이것들은 소프트웨어 밖의 현실 세계에는 존재하지 않는다. 단지 다른 객체와 함께 사용하기 위해 만들어낸 것이다. 그것들은 인공적이고 가짜 피조물이다. 

이런 문장이 있는걸 보면 저는 이 아티클에서 말하고자 하는 바는 현실 세계에서 개념을 그대로 가져와서 이해하는 것 같다고 생각하는데 어떻게 생각하시나유?

**Comment by wisemuji** [comment]
@shinsunyoung 

저는 객체를 설계할 때 현실 세계의 개념을 가져와서 객체지향 세계에 적용하되, 그 객체가 현실세계와 동일한 존재로 인식하면 안된다는 이야기로 이해했어요. 객체를 만들 때는 현실 세계를 기반으로 하지만 그 성격은 객체지향 세계에 맞게 변경할 수 있는거죠!

**Comment by shinsunyoung** [comment]
아하 이해 갔습니당 ㅎㅎ 감사해용 이슈는 닫도록 하겠습니다! 👍🙌🙏
